from datetime import date

from core.domain.models._displayed_provider import DisplayedProvider
from core.domain.models.model_data import (
    DeprecatedModel,
    LatestModel,
    MaxTokensData,
    ModelData,
    ModelFallback,
    ModelReasoningBudget,
    QualityData,
)
from core.domain.models.models import Model


def mistral_models() -> dict[Model, ModelData | LatestModel | DeprecatedModel]:
    return {
        Model.MIXTRAL_8X7B_32768: DeprecatedModel(
            replacement_model=Model.MISTRAL_SMALL_LATEST,
        ),
        Model.MISTRAL_LARGE_2_LATEST: LatestModel(
            model=Model.MISTRAL_LARGE_2_2407,
            display_name="Mistral Large 2 (latest)",
        ),
        Model.MISTRAL_LARGE_2_2407: ModelData(
            display_name="Mistral Large 2 (24-07)",
            supports_json_mode=True,
            supports_input_image=False,
            supports_input_pdf=False,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=131072,
                source="https://mistral.ai/news/mistral-large-2407/",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            latest_model=Model.MISTRAL_LARGE_2_LATEST,
            release_date=date(2024, 7, 24),
            quality_data=QualityData(mmlu=84, gpqa=46.09),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            fallback=ModelFallback.default("medium"),
        ),
        Model.MISTRAL_LARGE_LATEST: LatestModel(
            model=Model.MISTRAL_LARGE_2411,
            display_name="Mistral Large (latest)",
        ),
        Model.MISTRAL_LARGE_2411: ModelData(
            display_name="Mistral Large 2 (24-11)",
            supports_json_mode=True,
            supports_input_image=False,
            supports_input_pdf=False,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=131072,
                source="https://docs.mistral.ai/getting-started/models/",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            latest_model=Model.MISTRAL_LARGE_LATEST,
            release_date=date(2024, 11, 24),
            quality_data=QualityData(mmlu=84, gpqa=59.1),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            fallback=ModelFallback.default("medium"),
        ),
        Model.PIXTRAL_LARGE_LATEST: LatestModel(
            model=Model.PIXTRAL_LARGE_2411,
            display_name="PixTral Large (latest)",
        ),
        Model.PIXTRAL_LARGE_2411: ModelData(
            display_name="PixTral Large (24-11)",
            supports_json_mode=True,
            supports_input_image=True,
            supports_input_pdf=True,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=131072,
                source="https://docs.mistral.ai/getting-started/models/",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            latest_model=Model.PIXTRAL_LARGE_LATEST,
            release_date=date(2024, 11, 24),
            quality_data=QualityData(mmlu=70.1, gpqa=39.3),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            fallback=ModelFallback.default("medium"),
        ),
        Model.PIXTRAL_12B_2409: ModelData(
            display_name="PixTral (12B-2409)",
            supports_json_mode=True,
            supports_input_image=True,
            supports_input_pdf=True,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=131072,
                source="https://docs.mistral.ai/getting-started/models/",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            release_date=date(2024, 9, 17),
            quality_data=QualityData(mmlu=69.2, gpqa=39),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            fallback=ModelFallback.default("cheapest"),
        ),
        Model.MINISTRAL_3B_2410: ModelData(
            display_name="MiniStral (3B-2410)",
            supports_json_mode=True,
            supports_input_image=False,
            supports_input_pdf=False,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=131072,
                source="https://docs.mistral.ai/getting-started/models/",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            release_date=date(2024, 10, 24),
            quality_data=QualityData(mmlu=33.9, gpqa=33.59),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            fallback=ModelFallback.only_model(Model.GEMINI_2_0_FLASH_LITE_001, "cheapest"),
        ),
        Model.MINISTRAL_8B_2410: ModelData(
            display_name="MiniStral (8B-2410)",
            supports_json_mode=True,
            supports_input_image=False,
            supports_input_pdf=False,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=131072,
                source="https://docs.mistral.ai/getting-started/models/",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            release_date=date(2024, 10, 24),
            quality_data=QualityData(mmlu=63.4, gpqa=33.8),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            fallback=ModelFallback.default("cheapest"),
        ),
        Model.MISTRAL_SMALL_LATEST: ModelData(
            display_name="Mistral Small (latest)",
            supports_json_mode=True,
            supports_input_image=True,
            supports_input_pdf=True,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=131072,
                source="https://docs.mistral.ai/getting-started/models/",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            release_date=date(2025, 6, 11),
            quality_data=QualityData(mmlu=52.9, gpqa=33.8),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            fallback=ModelFallback.default("cheapest"),
        ),
        Model.MISTRAL_SMALL_2503: DeprecatedModel(
            replacement_model=Model.MISTRAL_SMALL_LATEST,
        ),
        Model.MISTRAL_SMALL_2501: DeprecatedModel(
            replacement_model=Model.MISTRAL_SMALL_LATEST,
        ),
        Model.MISTRAL_SMALL_2409: DeprecatedModel(
            replacement_model=Model.MISTRAL_SMALL_LATEST,
        ),
        Model.MISTRAL_SABA_2502: DeprecatedModel(
            replacement_model=Model.MISTRAL_SMALL_LATEST,
        ),
        Model.CODESTRAL_2501: DeprecatedModel(
            replacement_model=Model.CODESTRAL_LATEST,
        ),
        Model.CODESTRAL_LATEST: ModelData(
            display_name="CodeStral (latest)",
            supports_json_mode=True,
            supports_input_image=False,
            supports_input_pdf=False,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=262144,
                source="https://docs.mistral.ai/getting-started/models/",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            release_date=date(2025, 9, 30),
            quality_data=QualityData(mmlu=63.47, gpqa=38.35),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            fallback=ModelFallback.default("cheap"),
        ),
        Model.CODESTRAL_MAMBA_2407: ModelData(
            display_name="CodeStral Mamba (24-07)",
            supports_json_mode=True,
            supports_input_image=False,
            supports_input_pdf=False,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=262144,
                # source="https://docs.mistral.ai/getting-started/models/",
                source="https://api.mistral.ai/v1/models",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            release_date=date(2024, 7, 24),
            quality_data=QualityData(mmlu=63.47, gpqa=38.35),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            fallback=ModelFallback.default("cheapest"),
        ),
        Model.MISTRAL_MEDIUM_LATEST: ModelData(
            display_name="Mistral Medium 3 (25-05)",
            supports_json_mode=True,
            supports_input_image=True,
            supports_input_pdf=True,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=131072,
                # source="https://docs.mistral.ai/getting-started/models/",
                source="https://api.mistral.ai/v1/models",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            release_date=date(2025, 5, 8),
            quality_data=QualityData(
                mmlu_pro=77.2,
                gpqa_diamond=57.1,
                source="https://mistral.ai/news/mistral-medium-3",
            ),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            fallback=ModelFallback.default("cheap"),
        ),
        Model.MISTRAL_MEDIUM_2505: DeprecatedModel(
            replacement_model=Model.MISTRAL_MEDIUM_LATEST,
        ),
        Model.MAGISTRAL_SMALL_LATEST: ModelData(
            display_name="Magistral Small (latest)",
            supports_json_mode=True,
            supports_input_image=True,
            supports_input_pdf=True,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=40_960,
                source="https://docs.mistral.ai/getting-started/models/models_overview/",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            release_date=date(2025, 9, 11),
            quality_data=QualityData(
                gpqa_diamond=68.18,
                source="https://huggingface.co/mistralai/Magistral-Small-2506",
            ),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            # Magistral does not support configuring a reasoning budget or effort
            reasoning=ModelReasoningBudget(disabled=None, low=None, medium=None, high=None),
            fallback=ModelFallback.default("cheap"),
        ),
        Model.MAGISTRAL_SMALL_2506: DeprecatedModel(
            replacement_model=Model.MAGISTRAL_SMALL_LATEST,
        ),
        Model.MAGISTRAL_MEDIUM_LATEST: ModelData(
            display_name="Magistral Medium (latest)",
            supports_json_mode=True,
            supports_input_image=True,
            supports_input_pdf=True,
            supports_input_audio=False,
            max_tokens_data=MaxTokensData(
                max_tokens=40_960,
                source="https://docs.mistral.ai/getting-started/models/models_overview/",
            ),
            icon_url="https://workflowai.blob.core.windows.net/workflowai-public/mistral.svg",
            release_date=date(2025, 9, 1),
            quality_data=QualityData(
                gpqa_diamond=79.8,
                source="https://mistral.ai/news/magistral",
            ),
            provider_name=DisplayedProvider.MISTRAL_AI.value,
            supports_tool_calling=True,
            # Magistral does not support configuring a reasoning budget or effort
            reasoning=ModelReasoningBudget(disabled=None, low=None, medium=None, high=None),
            fallback=ModelFallback.default("medium"),
        ),
        Model.MAGISTRAL_MEDIUM_2506: DeprecatedModel(
            replacement_model=Model.MAGISTRAL_MEDIUM_LATEST,
        ),
    }
